### ISSUE TITLE
Offer a `setup-oc` action

### ISSUE THREAD

**Issue by nymous** [redhat-developer/openshift-actions#28]
Extracting the download & installation logic from this action to provide an action similar to the [setup-node](https://github.com/actions/setup-node) or [setup-python](https://github.com/actions/setup-python) actions would be useful for two cases:
- offer a workaround for #13 by using directly the `oc` CLI in later scripts, eg:
```yaml
- uses: redhat-developer/setup-oc
  with:
    version: '3.11.36'
- run: oc version > version.txt
```
- allow us to use the preinstalled `helm` to deploy to Openshift cluster, eg:
```yaml
- uses: redhat-developer/setup-oc
  with:
    version: '3.11.36'
- run: |
    oc login ...
    helm upgrade --install chart
```

**Comment by lstocchi** [comment]
Thanks for opening the issue @nymous and sorry for the late response. We discussed about it and we decided to add a new feature to the existing action to allow users to just use the download and installation logic. 

Adding it to our sprint.

**Comment by lstocchi** [comment]
Hello @nymous , 
we finally released a new version of the action. It now allows you to set up oc and use it in the following scripts.

```
    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v2.1.0
      with:
        version: '3.11.90'
    - name: followingScript
      run: |
        oc login --token=${{ secrets.API_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER_URL }}
        oc get pods | grep build
```

The new version is the `v2.1.0`.
I'm closing this issue but if you find any problem about setting up oc or you have any feedback feel free to reopen this. 
Thanks again for your message and sorry again for the late response :)
