### ISSUE TITLE
Error: Unexpected HTTP response: 404

### ISSUE THREAD

**Issue by DarkLite1** [redhat-developer/openshift-actions#40]
On GitHub when triggering an `Action` we get this error:
![image](https://user-images.githubusercontent.com/10828570/92394871-a3f2c580-f122-11ea-9ea0-fb8715031e03.png)

Following the [docs](https://developers.redhat.com/blog/2020/02/13/openshift-actions-deploy-to-red-hat-openshift-directly-from-your-github-repository/) we created the two `secrets` in GitHub, the ones copied from `OpenShift > Copy Login Command` when clicking the name in the upper right corner within the OpenShift web portal:

![image](https://user-images.githubusercontent.com/10828570/92395131-1e234a00-f123-11ea-8f9a-365b9b8ce0d6.png)

When logging in manually from the console with PowerShell all works fine with the same token and URL (`https://console.dev02-xxxxxxxxs.me:443`):
```powershell
oc login $Env:OPENSHIFT_SERVER_URL --token=$Env:OPENSHIFT_API_TOKEN
```

Running `oc version`:
```
Client Version: 4.5.7
Kubernetes Version: v1.11.0+d4cacc0
```

This makes me believe that the following config is correct:
```yml
      - name: OpenShift Action
        uses: redhat-developer/openshift-actions@v2.1.0
        with:
          version: '3.11.0'
```

**main.yml`**
```yml
# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow 
# on push or pull request events but only for the master branch
on:
  # trigger the workflow on GitHub via Actions
  workflow_dispatch:
  # trigger the workflow outside of GitHub (PowerShell, ...)
  repository_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Run OpenShift build process
      - name: OpenShift Action
        uses: redhat-developer/openshift-actions@v2.1.0
        with:
          version: '3.11.0'
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT_API_TOKEN }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
```

I've noticed that the [share](https://mirror.openshift.com/pub/openshift-v3/clients/) does not contain a version called `3.11..0` so when correcting it to `3.11.0-0.32.0` we get this error:
![image](https://user-images.githubusercontent.com/10828570/92397864-cdfab680-f127-11ea-8b6a-cb0505336345.png)

![image](https://user-images.githubusercontent.com/10828570/92398108-3c3f7900-f128-11ea-98e8-3f79185b0e2d.png)

Am I missing somethng? Thank you for your help.

**Comment by lstocchi** [comment]
Hi @DarkLite1 ,

the issue is the oc version you want to use. 
The action downloads the oc cli from https://mirror.openshift.com/pub/openshift-v3/clients and the version 3.11.0 (the folder with this name) doesn't exist. I guess I could improve this process a bit by adding a better message/handle it automatically but as a quick fix you can try to use another version.

A suggestion is to use a newer release (e.g from 3.11.230) as the old ones come with an issue in ubuntu https://github.com/openshift/origin/issues/21061
` error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory`

So try to rewrite your yaml to
```
- name: OpenShift Action
        uses: redhat-developer/openshift-actions@v2.1.0
        with:
          version: '3.11.230'
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT_API_TOKEN }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
```

It should work. Let me know :)
