### ISSUE TITLE
[Documentation]Full working example

### ISSUE THREAD

**Issue by DarkLite1** [redhat-developer/openshift-actions#41]
Thank you for the great tool, it really helps a newbie like me to get my project up and running in OpenShift. For the moment we have a node.js app ready to deploy and we're a bit stuck in how this is best done. So my question is: Would it be possible to add a complete example of a GitHub Action with OpenShift for a node.js app?

We [found](https://resources.github.com/whitepapers/GitHub-Actions-Cheat-sheet/) a `.yml` config like this:
```yml
name: CI for Node.js Project
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
    - uses: actions/checkout@v2
      name: Check out repository
    - uses: actions/setup-node@v1
      name: Set up Node.js
      with:
        node-version: 12
    - run: |
        npm ci
        npm run build
        npm test
      name: Build and Test
```

But it is not using a Docker image, the OpenShift Action or anything else. So we're wondering how to get something like this on the OpenShift platform? 

Sorry if these are stupid questions, we're just starting out and trying to get an understanding on how it all fits together. The issue is also that we don't have a Linux host or Win Srv 2019 with wsl2 at our disposal within the company but this isn't even required I believe for OpenShift as we can just use a dockerfile and have it all generated on the platform using the GitHub Actions?

Anyway, thanks for maybe adding a more complete flow

**Comment by lstocchi** [comment]
@DarkLite1 what i usually do is to first setup my app on OpenShift so something like 

```
oc new-app my-amazing-repo-url --name=mycustomname
oc expose svc/mycustomname
```

now you should have your basic app on OpenShift. 
After that, i would setup my action to update myapp everytime i merge something into the master.

```
- name: OpenShift Action
      uses: redhat-developer/openshift-actions@v2.1.0
      with:
        version: '3.11.230'
        openshift_server_url: ${{ secrets.CRC_OPENSHIFT_URL }}
        parameters: '{"apitoken": "${{ secrets.CRC_TOKEN }}", "acceptUntrustedCerts": "true"}'
        cmd: |
          oc project your-project-here
          oc start-build mycustomname --from-repo ${GITHUB_WORKSPACE} --follow
```

Basically what happens is ... the new-app command executed at the beginning creates all resources needed by our app by using the source code (it recognizes the language and handle the build). 
Among those resources created there is the deployment config (that deploy the new image) which gets triggered everytime our imagestream is updated. 
We then use this behavior to update our app with the `start-build` command which start a new build -> update the imagestream -> deploy the new image.
The GITHUB_WORKSPACE is the folder where the checkout action downloads the repo code.

Not sure if it's clear ... If you want/can, you could also send me your repo url and i can make an example with that

**Comment by DarkLite1** [comment]
Thank you very much for this detailed example. It really clears things up a bit for me. 

The only issue then left is that we can't simply do `npm run start` as in the example app but we need to run `quasar build` first. So the [Quasar Framework can build](https://quasar.dev/quasar-cli/build-commands) the app. That's why I thought I needed to build my own image with Docker, which is a bit of a pain when not on a Linux supported host.

Actually it would be great if something like this would be possible in the GitHub action:
```
- name: OpenShift Action
      uses: redhat-developer/openshift-actions@v2.1.0
      with:
        version: '3.11.230'
        openshift_server_url: ${{ secrets.CRC_OPENSHIFT_URL }}
        parameters: '{"apitoken": "${{ secrets.CRC_TOKEN }}", "acceptUntrustedCerts": "true"}'
        cmd: |
          oc project hip
          quasar build
          oc start-build hip-frontend --from-repo ${GITHUB_WORKSPACE} --follow
```

My [GitHub repo](https://github.com/DarkLite1/hip) for clarity.

**Comment by lstocchi** [comment]
Sorry for the late response @DarkLite1, i've been stuck on another thing.
 
I think i got what's your issue. You want to deploy static files (html/js) built by Quasar.
Bad news is that i never did that before... but there are a lot of resources out there.

You can look at https://developers.redhat.com/blog/2018/10/23/modern-web-applications-on-openshift-part-2-using-chained-builds/ as an example. 

I only tried following this by executing the commands manually but I guess it can be converted to an action workflow once you have this working.

N.B: In the tutorial they talk about a react web app but if you add the build command in your package.json to use quasar, it works fine `"build": "quasar build",`. 

I'll try to make a working example in the next days and put it in the repo but atleast you now have a hint how to go forward.

**Comment by DarkLite1** [comment]
This looks promising! The only downside is that it relies on `GitHub Webhook` which isn't so customisable as `GitHub Actions`. Ideally it would be great if the code on OpenShift would only be updated when pushing to the `master` or `production` branch. This seems to be not possible with a `GitHub Webook`.

I'm also thinking it might be simpler to create a simple `Dockerfile` and push the complete image to the Docker hub. It would make it possible to run the image independent of OpenShift. No vendor lock-in this way and easier to test when things go wrong. Is it the image? Is it OpenShift? The downside of this approach is speed. We can't leverage the caching mechanism of OpenShift with this method, but we're not really bothered with a cycle that takes 5 minutes instead of 1 minute.

It also seems very complex to set up such an `application.yaml` file... But that might be me being inexperienced.  It also seems cool to see progress on GitHub. Still thinking.... Thanks anyway for the big help.

**Comment by lstocchi** [comment]
Keep in mind that that's a template and it can be customized. The cool part is that it uses the buildconfigs/deploymentconfig that are executed automatically once the first is triggered. 

In the tutorial everything is showed well but let me explain the idea behind this.

> A quick lesson. 
> 1. A buildconfig is a definition of how to perform a build. What we say by creating a build config is ... my dear OpenShift when i start a new build with this configuration does what you read in it. 
> In this example, OpenShift will see that we are expecting it to take the source code from the git repo ${SOURCE_REPOSITORY_URL}, that we want to create (output) an image as the result by using the source strategy. 
> 
> 2. The deployment config is similar but it is responsible to deploy your application.


The normal flow of this is
first build config gets executed -> finishes to create a resulting image -> the second build gets triggered -> finishes creating the resulting image -> the deployment config gets triggered -> our app is deployed.

So if you delete all triggers from the first build config it will never start by itself but you are responsible of it.

Here you can make use of the github action by forcing the start of a new-build with
`oc start-build thenameofthebuild`

I know it's hard if you are not used to OpenShift. I'll start working on an example now

**Comment by DarkLite1** [comment]
So I tried to follow your advice. There's no need for a `GitHub Webhook` so I removed that parameter and end up with the triggers below. I'll probably rename everything `react` to `vue` for clarity:

```yaml
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: react-web-app-builder
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: react-web-app-builder:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: OUTPUT_DIR
            value: ${OUTPUT_DIR}
        from:
          kind: ImageStreamTag
          name: web-app-s2i-image:latest
        incremental: true
      type: Source
    triggers: {}
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: static-web-app-running-on-nginx
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: static-web-app-running-on-nginx:latest
    postCommit: {}
    resources: {}
    source:
      type: Image
      images:
        - from:
            kind: ImageStreamTag
            name: react-web-app-builder:latest
          paths:
            - destinationDir: .
              sourcePath: /opt/app-root/output/.
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nginx-image-runtime:latest
        incremental: true
      type: Source
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: react-web-app-builder:latest
  status:
    lastVersion: 0
```

When this template works I'll upload it to the project and can use it for other `Vue.js` projects, even the ones created by the Quasar Framework. I just need to have in my `pacakge.json` the `build` script correctly set. And then feed the template the correct build folder. 

So as I see it now:

1. Create a template that works and takes a build folder as parameter
2. Upload the template to OpenShift
3. Create the app in OpenShift based on the template (one app frontend, one backend)
4. Set the `GitHub Actions` to trigger a new OpenShift build on push to `master` branch

**Comment by lstocchi** [comment]
Below an example. To being faster i only edited the template from the article (but you can also create all resources by hand) and used a sample vue app (i tried to compile yours but i got an error, probably because of my environment but i didn't want to spend time investigating on it), the outcome should be the same with your app.

The edited template is at the end of this post (because of its length). The only change is its name (i removed the react label), the default value of the OUTPUT_DIR to `dist/spa` (i saw that quasar put the compiled files there) and the triggers (i removed all of them) from the first buildconfig.

1) First you need to create the template 
`oc create -f template.yaml` (change the filename based on your system)

2) Then you need to create all resources by using the template
`oc new-app --template quasar-web-app -p SOURCE_REPOSITORY_URL=https://github.com/lstocchi/quasar-geolocation-example.git --name=myquasarapp`

Because i removed all triggers from the first build config, you will only see new resources created. Nothing will get started. You are responsible of trigger it.

3) Add the build command yo your package.json app
`"build": "quasar build",` -> this will get called automatically during the first build (the exact call is npm run build, so put here the command you want to get executed to compile your app)

4) To trigger the build just use
`oc start-build quasar-web-app-builder` -> it will first compile your app -> at the end it will trigger the second build which will create the real image to be deployed

Now, in your github workflow you can just add the (4) command, because you already have all resources needed and you need only to trigger them.

```
- name: OpenShift Action
      uses: redhat-developer/openshift-actions@v2.1.0
      with:
        version: '3.11.230'
        openshift_server_url: ${{ secrets.CRC_OPENSHIFT_URL }}
        parameters: '{"apitoken": "${{ secrets.CRC_TOKEN }}", "acceptUntrustedCerts": "true"}'
        cmd: |
          oc project ${PROJECT}
          oc start-build quasar-web-app-builder --follow
```

So when something is merged in your repo -> the action will trigger the build -> you should see the new app deployed + the logs in github

```
apiVersion: v1
kind: Template
metadata:
  name: quasar-web-app
parameters:
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    value: ""
    required: true
  - name: SOURCE_REPOSITORY_REF
    description: The branch name for the application
    displayName: Source Branch
    value: master
    required: true
  - name: SOURCE_REPOSITORY_DIR
    description: The location within the source repo of the application
    displayName: Source Directory
    value: .
    required: true
  - name: OUTPUT_DIR
    description: The location of the compiled static files from your web apps builder
    displayName: Output Directory
    value: dist/spa
    required: false
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: quasar-web-app-builder
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: static-web-app-running-on-nginx
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: web-app-s2i-image
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: nodeshift/centos7-s2i-web-app:10.x
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: nginx-image-runtime
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'centos/nginx-112-centos7:latest'
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: quasar-web-app-builder
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: quasar-web-app-builder:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: OUTPUT_DIR
            value: ${OUTPUT_DIR}
        from:
          kind: ImageStreamTag
          name: web-app-s2i-image:latest
        incremental: true
      type: Source 
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: static-web-app-running-on-nginx
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: static-web-app-running-on-nginx:latest
    postCommit: {}
    resources: {}
    source:
      type: Image
      images:
        - from:
            kind: ImageStreamTag
            name: quasar-web-app-builder:latest
          paths:
            - destinationDir: .
              sourcePath: /opt/app-root/output/.
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nginx-image-runtime:latest
        incremental: true
      type: Source
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: quasar-web-app-builder:latest
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: quasar-web-app
    name: quasar-web-app
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: quasar-web-app
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: quasar-web-app
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: static-web-app-running-on-nginx
          imagePullPolicy: IfNotPresent
          name: static-web-app-running-on-nginx
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - static-web-app-running-on-nginx
          from:
            kind: ImageStreamTag
            name: 'static-web-app-running-on-nginx:latest'
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: quasar-web-app
    name: quasar-web-app
  spec:
    ports:
    - name: http
      port: 8080
    selector:
      app: quasar-web-app
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: quasar-web-app
    name: quasar-web-app
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: quasar-web-app
```

**Comment by lstocchi** [comment]
> So I tried to follow your advice. There's no need for a `GitHub Webhook` so I removed that parameter and end up with the triggers below. I'll probably rename everything `react` to `vue` for clarity:
> 
 exactly :+1:
> 
> When this template works I'll upload it to the project and can use it for other `Vue.js` projects, even the ones created by the Quasar Framework. I just need to have in my `pacakge.json` the `build` script correctly set. 

:+1:
> 
> So as I see it now:
> 
> 1. Create a template that works and takes a build folder as parameter
> 2. Upload the template to OpenShift
> 3. Create the app in OpenShift based on the template (one app frontend, one backend)
> 4. Set the `GitHub Actions` to trigger a new OpenShift build on push to `master` branch

I think you would need something different for the backend but it's correct for the frontend
:+1:

**Comment by lstocchi** [comment]
Last thing... during my test i saw some of my pods failing with this error `The node was low on resource: ephemeral-storage`.
Not sure if it was me because i'm working on my local machine and i have some limitations but ... if you face this, you could define a limit which will overwrite the default limitation rule and it should work.

`oc patch bc quasar-web-app-builder -p '{"spec":{"resources":{"limits":{"ephemeral-storage":"5Gi"}}}}'`
`oc patch bc static-web-app-running-on-nginx -p '{"spec":{"resources":{"limits":{"ephemeral-storage":"5Gi"}}}}'`

**Comment by DarkLite1** [comment]
Awesome! The deployment worked out perfectly! Need to iron out some kinks here and there but it is up and running. So thank you very much for the help. One strange thing for having it triggered by `GitHub Actions` is this:

![image](https://user-images.githubusercontent.com/10828570/92595721-1a1f3580-f2a5-11ea-9b5b-271d355b87e7.png)

```
      # Run OpenShift build process
      - name: OpenShift Action
        uses: redhat-developer/openshift-actions@v2.1.0
        with:
          version: '3.11.230'
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT_API_TOKEN }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            oc project ${PROJECT}
            oc start-build quasar-web-app-builder --follow
```

It seems to authenticate fine but it says we're not a member. Although I think we created the `robot` user correctly:
```powershell
# create OpenShift API token for project hip
oc create serviceaccount robot
oc policy add-role-to-user admin system:serviceaccount:hip:robot
oc serviceaccounts get-token robot
```

**Comment by lstocchi** [comment]
@DarkLite1 did you use an env variable to give a value to PROJECT variable?

I didn't mention it in my previous comment but the `${}` syntax is used for variable substitution. You should have something like 
```
env:
  PROJECT: hip

jobs:
  build:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Run OpenShift build process
      - name: OpenShift Action
        uses: redhat-developer/openshift-actions@v2.1.0
        with:
          version: '3.11.230'
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT_API_TOKEN }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            oc project ${PROJECT}
            oc start-build quasar-web-app-builder --follow
```

but you can also change the command directly with `oc project hip`.

I guess this is the issue you have. Sorry for not have mentioned it. Let me know if it works.
