### ISSUE TITLE
The `add-path` command is disabled

### ISSUE THREAD

**Issue by DarkLite1** [redhat-developer/openshift-actions#64]
Since today we receive the following error when triggering a new build with GitHub Actions:
```
Unable to process command '::add-path::/home/runner/work/_temp/1d927908-5f05-4a72-851f-c106a7be6583' successfully.
The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**CD.yml**
```
name: Continuous deployment

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Run OpenShift build process
      - name: Start OpenShift build
        uses: redhat-developer/openshift-actions@v2.1.0
        with:
          version: '3.11.230'
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT_API_TOKEN }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            oc project hip
            oc start-build backend-graphql-server --follow
```

A similar issue has been reported [here](https://github.com/djjudas21/camerahub/issues/630) for another project. So at this time we are now longer able to publish new version to OpenShift.

Thank you for having a look at this.

**Comment by lstocchi** [comment]
@DarkLite1 we are working on a new set of gh actions so this one if going to be deprecated soon. What i can suggest you is to change a bit you workflow for the moment this way. 

```
name: Continuous deployment

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Run OpenShift build process
     - name: Install oc
       uses: redhat-actions/oc-installer@v1
       with:
         version: '3.11.230'         
     - name: Execute oc commands
       run: |
         oc login --insecure-skip-tls-verify --token ${{ secrets.OPENSHIFT_API_TOKEN }} ${{ secrets.OPENSHIFT_SERVER_URL }}
         oc project hip
         oc start-build backend-graphql-server --follow
```

For the new coming actions give a look at https://github.com/redhat-actions ;)
Then not sure if using the oc 3.11.230 is a real need but if you are using the latest ubuntu environment it already comes with oc (4.5) pre-installed and you can skip the installation step https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#cli-tools

**Comment by DarkLite1** [comment]
Thank you for getting back to me. 

Using this:
```jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      Run OpenShift build process    
     - name: Execute oc commands
       run: |
         oc login --insecure-skip-tls-verify --token ${{ secrets.OPENSHIFT_API_TOKEN }} ${{ secrets.OPENSHIFT_SERVER_URL }}
         oc project hip
         oc start-build backend-graphql-server --follow
```

Fails with the error below while I'm 100% certain we have a project:
![image](https://user-images.githubusercontent.com/10828570/99374541-f5f25d00-28c2-11eb-8c32-876174902d71.png)

Using this config:
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      Run OpenShift build process
       - name: Install oc
         uses: redhat-actions/oc-installer@v1
         with:
           oc_version: '3.11.230'         
     - name: Execute oc commands
       run: |
         oc login --insecure-skip-tls-verify --token ${{ secrets.OPENSHIFT_API_TOKEN }} ${{ secrets.OPENSHIFT_SERVER_URL }}
         oc project hip
         oc start-build backend-graphql-server --follow
```

Also fails:
![image](https://user-images.githubusercontent.com/10828570/99375042-8d57b000-28c3-11eb-81db-a5f3a6792a07.png)


*I had to rename `version` to `oc_version`. Can you see where I'm going wrong?
